/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as MapRouteImport } from './routes/map'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestgrowthIndexRouteImport } from './routes/guestgrowth/index'
import { Route as WifiSlugRouteImport } from './routes/wifi.$slug'
import { Route as PlaqueSlugRouteImport } from './routes/plaque.$slug'
import { Route as ListingsSlugRouteImport } from './routes/listings.$slug'
import { Route as GuestgrowthSampleRouteImport } from './routes/guestgrowth/sample'
import { Route as ExploreSlugRouteImport } from './routes/explore.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog.rss[.]xml'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as DevEmailPreviewTemplateRouteImport } from './routes/dev/email-preview.$template'
import { Route as ApiPublicWifiSignupRouteImport } from './routes/api/public/wifi-signup'
import { Route as ApiPublicRefreshReviewsRouteImport } from './routes/api/public/refresh-reviews'
import { Route as ApiPublicRebookingCampaignRouteImport } from './routes/api/public/rebooking-campaign'
import { Route as ApiPublicProcessUpsellRepliesRouteImport } from './routes/api/public/process-upsell-replies'
import { Route as ApiPublicPreArrivalMessageRouteImport } from './routes/api/public/pre-arrival-message'
import { Route as ApiPublicPostCheckoutMessageRouteImport } from './routes/api/public/post-checkout-message'
import { Route as ApiPublicOrphanDayUpsellRouteImport } from './routes/api/public/orphan-day-upsell'
import { Route as ApiPublicGuestgrowthLeadRouteImport } from './routes/api/public/guestgrowth-lead'
import { Route as ApiPublicDiscountSignupRouteImport } from './routes/api/public/discount-signup'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestgrowthIndexRoute = GuestgrowthIndexRouteImport.update({
  id: '/guestgrowth/',
  path: '/guestgrowth/',
  getParentRoute: () => rootRouteImport,
} as any)
const WifiSlugRoute = WifiSlugRouteImport.update({
  id: '/wifi/$slug',
  path: '/wifi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaqueSlugRoute = PlaqueSlugRouteImport.update({
  id: '/plaque/$slug',
  path: '/plaque/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsSlugRoute = ListingsSlugRouteImport.update({
  id: '/listings/$slug',
  path: '/listings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestgrowthSampleRoute = GuestgrowthSampleRouteImport.update({
  id: '/guestgrowth/sample',
  path: '/guestgrowth/sample',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExploreRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const DevEmailPreviewTemplateRoute = DevEmailPreviewTemplateRouteImport.update({
  id: '/dev/email-preview/$template',
  path: '/dev/email-preview/$template',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWifiSignupRoute = ApiPublicWifiSignupRouteImport.update({
  id: '/api/public/wifi-signup',
  path: '/api/public/wifi-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshReviewsRoute = ApiPublicRefreshReviewsRouteImport.update({
  id: '/api/public/refresh-reviews',
  path: '/api/public/refresh-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRebookingCampaignRoute =
  ApiPublicRebookingCampaignRouteImport.update({
    id: '/api/public/rebooking-campaign',
    path: '/api/public/rebooking-campaign',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProcessUpsellRepliesRoute =
  ApiPublicProcessUpsellRepliesRouteImport.update({
    id: '/api/public/process-upsell-replies',
    path: '/api/public/process-upsell-replies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPreArrivalMessageRoute =
  ApiPublicPreArrivalMessageRouteImport.update({
    id: '/api/public/pre-arrival-message',
    path: '/api/public/pre-arrival-message',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPostCheckoutMessageRoute =
  ApiPublicPostCheckoutMessageRouteImport.update({
    id: '/api/public/post-checkout-message',
    path: '/api/public/post-checkout-message',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOrphanDayUpsellRoute =
  ApiPublicOrphanDayUpsellRouteImport.update({
    id: '/api/public/orphan-day-upsell',
    path: '/api/public/orphan-day-upsell',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGuestgrowthLeadRoute =
  ApiPublicGuestgrowthLeadRouteImport.update({
    id: '/api/public/guestgrowth-lead',
    path: '/api/public/guestgrowth-lead',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscountSignupRoute = ApiPublicDiscountSignupRouteImport.update({
  id: '/api/public/discount-signup',
  path: '/api/public/discount-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRouteWithChildren
  '/map': typeof MapRoute
  '/properties': typeof PropertiesRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/guestgrowth/sample': typeof GuestgrowthSampleRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/plaque/$slug': typeof PlaqueSlugRoute
  '/wifi/$slug': typeof WifiSlugRoute
  '/guestgrowth/': typeof GuestgrowthIndexRoute
  '/api/public/discount-signup': typeof ApiPublicDiscountSignupRoute
  '/api/public/guestgrowth-lead': typeof ApiPublicGuestgrowthLeadRoute
  '/api/public/orphan-day-upsell': typeof ApiPublicOrphanDayUpsellRoute
  '/api/public/post-checkout-message': typeof ApiPublicPostCheckoutMessageRoute
  '/api/public/pre-arrival-message': typeof ApiPublicPreArrivalMessageRoute
  '/api/public/process-upsell-replies': typeof ApiPublicProcessUpsellRepliesRoute
  '/api/public/rebooking-campaign': typeof ApiPublicRebookingCampaignRoute
  '/api/public/refresh-reviews': typeof ApiPublicRefreshReviewsRoute
  '/api/public/wifi-signup': typeof ApiPublicWifiSignupRoute
  '/dev/email-preview/$template': typeof DevEmailPreviewTemplateRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRouteWithChildren
  '/map': typeof MapRoute
  '/properties': typeof PropertiesRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/guestgrowth/sample': typeof GuestgrowthSampleRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/plaque/$slug': typeof PlaqueSlugRoute
  '/wifi/$slug': typeof WifiSlugRoute
  '/guestgrowth': typeof GuestgrowthIndexRoute
  '/api/public/discount-signup': typeof ApiPublicDiscountSignupRoute
  '/api/public/guestgrowth-lead': typeof ApiPublicGuestgrowthLeadRoute
  '/api/public/orphan-day-upsell': typeof ApiPublicOrphanDayUpsellRoute
  '/api/public/post-checkout-message': typeof ApiPublicPostCheckoutMessageRoute
  '/api/public/pre-arrival-message': typeof ApiPublicPreArrivalMessageRoute
  '/api/public/process-upsell-replies': typeof ApiPublicProcessUpsellRepliesRoute
  '/api/public/rebooking-campaign': typeof ApiPublicRebookingCampaignRoute
  '/api/public/refresh-reviews': typeof ApiPublicRefreshReviewsRoute
  '/api/public/wifi-signup': typeof ApiPublicWifiSignupRoute
  '/dev/email-preview/$template': typeof DevEmailPreviewTemplateRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRouteWithChildren
  '/map': typeof MapRoute
  '/properties': typeof PropertiesRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/guestgrowth/sample': typeof GuestgrowthSampleRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/plaque/$slug': typeof PlaqueSlugRoute
  '/wifi/$slug': typeof WifiSlugRoute
  '/guestgrowth/': typeof GuestgrowthIndexRoute
  '/api/public/discount-signup': typeof ApiPublicDiscountSignupRoute
  '/api/public/guestgrowth-lead': typeof ApiPublicGuestgrowthLeadRoute
  '/api/public/orphan-day-upsell': typeof ApiPublicOrphanDayUpsellRoute
  '/api/public/post-checkout-message': typeof ApiPublicPostCheckoutMessageRoute
  '/api/public/pre-arrival-message': typeof ApiPublicPreArrivalMessageRoute
  '/api/public/process-upsell-replies': typeof ApiPublicProcessUpsellRepliesRoute
  '/api/public/rebooking-campaign': typeof ApiPublicRebookingCampaignRoute
  '/api/public/refresh-reviews': typeof ApiPublicRefreshReviewsRoute
  '/api/public/wifi-signup': typeof ApiPublicWifiSignupRoute
  '/dev/email-preview/$template': typeof DevEmailPreviewTemplateRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/explore'
    | '/map'
    | '/properties'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/email/unsubscribe'
    | '/explore/$slug'
    | '/guestgrowth/sample'
    | '/listings/$slug'
    | '/plaque/$slug'
    | '/wifi/$slug'
    | '/guestgrowth/'
    | '/api/public/discount-signup'
    | '/api/public/guestgrowth-lead'
    | '/api/public/orphan-day-upsell'
    | '/api/public/post-checkout-message'
    | '/api/public/pre-arrival-message'
    | '/api/public/process-upsell-replies'
    | '/api/public/rebooking-campaign'
    | '/api/public/refresh-reviews'
    | '/api/public/wifi-signup'
    | '/dev/email-preview/$template'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/explore'
    | '/map'
    | '/properties'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/email/unsubscribe'
    | '/explore/$slug'
    | '/guestgrowth/sample'
    | '/listings/$slug'
    | '/plaque/$slug'
    | '/wifi/$slug'
    | '/guestgrowth'
    | '/api/public/discount-signup'
    | '/api/public/guestgrowth-lead'
    | '/api/public/orphan-day-upsell'
    | '/api/public/post-checkout-message'
    | '/api/public/pre-arrival-message'
    | '/api/public/process-upsell-replies'
    | '/api/public/rebooking-campaign'
    | '/api/public/refresh-reviews'
    | '/api/public/wifi-signup'
    | '/dev/email-preview/$template'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/explore'
    | '/map'
    | '/properties'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/email/unsubscribe'
    | '/explore/$slug'
    | '/guestgrowth/sample'
    | '/listings/$slug'
    | '/plaque/$slug'
    | '/wifi/$slug'
    | '/guestgrowth/'
    | '/api/public/discount-signup'
    | '/api/public/guestgrowth-lead'
    | '/api/public/orphan-day-upsell'
    | '/api/public/post-checkout-message'
    | '/api/public/pre-arrival-message'
    | '/api/public/process-upsell-replies'
    | '/api/public/rebooking-campaign'
    | '/api/public/refresh-reviews'
    | '/api/public/wifi-signup'
    | '/dev/email-preview/$template'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  MapRoute: typeof MapRoute
  PropertiesRoute: typeof PropertiesRoute
  ReviewsRoute: typeof ReviewsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GuestgrowthSampleRoute: typeof GuestgrowthSampleRoute
  ListingsSlugRoute: typeof ListingsSlugRoute
  PlaqueSlugRoute: typeof PlaqueSlugRoute
  WifiSlugRoute: typeof WifiSlugRoute
  GuestgrowthIndexRoute: typeof GuestgrowthIndexRoute
  ApiPublicDiscountSignupRoute: typeof ApiPublicDiscountSignupRoute
  ApiPublicGuestgrowthLeadRoute: typeof ApiPublicGuestgrowthLeadRoute
  ApiPublicOrphanDayUpsellRoute: typeof ApiPublicOrphanDayUpsellRoute
  ApiPublicPostCheckoutMessageRoute: typeof ApiPublicPostCheckoutMessageRoute
  ApiPublicPreArrivalMessageRoute: typeof ApiPublicPreArrivalMessageRoute
  ApiPublicProcessUpsellRepliesRoute: typeof ApiPublicProcessUpsellRepliesRoute
  ApiPublicRebookingCampaignRoute: typeof ApiPublicRebookingCampaignRoute
  ApiPublicRefreshReviewsRoute: typeof ApiPublicRefreshReviewsRoute
  ApiPublicWifiSignupRoute: typeof ApiPublicWifiSignupRoute
  DevEmailPreviewTemplateRoute: typeof DevEmailPreviewTemplateRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestgrowth/': {
      id: '/guestgrowth/'
      path: '/guestgrowth'
      fullPath: '/guestgrowth/'
      preLoaderRoute: typeof GuestgrowthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wifi/$slug': {
      id: '/wifi/$slug'
      path: '/wifi/$slug'
      fullPath: '/wifi/$slug'
      preLoaderRoute: typeof WifiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plaque/$slug': {
      id: '/plaque/$slug'
      path: '/plaque/$slug'
      fullPath: '/plaque/$slug'
      preLoaderRoute: typeof PlaqueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$slug': {
      id: '/listings/$slug'
      path: '/listings/$slug'
      fullPath: '/listings/$slug'
      preLoaderRoute: typeof ListingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestgrowth/sample': {
      id: '/guestgrowth/sample'
      path: '/guestgrowth/sample'
      fullPath: '/guestgrowth/sample'
      preLoaderRoute: typeof GuestgrowthSampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$slug': {
      id: '/explore/$slug'
      path: '/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/email-preview/$template': {
      id: '/dev/email-preview/$template'
      path: '/dev/email-preview/$template'
      fullPath: '/dev/email-preview/$template'
      preLoaderRoute: typeof DevEmailPreviewTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wifi-signup': {
      id: '/api/public/wifi-signup'
      path: '/api/public/wifi-signup'
      fullPath: '/api/public/wifi-signup'
      preLoaderRoute: typeof ApiPublicWifiSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-reviews': {
      id: '/api/public/refresh-reviews'
      path: '/api/public/refresh-reviews'
      fullPath: '/api/public/refresh-reviews'
      preLoaderRoute: typeof ApiPublicRefreshReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rebooking-campaign': {
      id: '/api/public/rebooking-campaign'
      path: '/api/public/rebooking-campaign'
      fullPath: '/api/public/rebooking-campaign'
      preLoaderRoute: typeof ApiPublicRebookingCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-upsell-replies': {
      id: '/api/public/process-upsell-replies'
      path: '/api/public/process-upsell-replies'
      fullPath: '/api/public/process-upsell-replies'
      preLoaderRoute: typeof ApiPublicProcessUpsellRepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pre-arrival-message': {
      id: '/api/public/pre-arrival-message'
      path: '/api/public/pre-arrival-message'
      fullPath: '/api/public/pre-arrival-message'
      preLoaderRoute: typeof ApiPublicPreArrivalMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/post-checkout-message': {
      id: '/api/public/post-checkout-message'
      path: '/api/public/post-checkout-message'
      fullPath: '/api/public/post-checkout-message'
      preLoaderRoute: typeof ApiPublicPostCheckoutMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orphan-day-upsell': {
      id: '/api/public/orphan-day-upsell'
      path: '/api/public/orphan-day-upsell'
      fullPath: '/api/public/orphan-day-upsell'
      preLoaderRoute: typeof ApiPublicOrphanDayUpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guestgrowth-lead': {
      id: '/api/public/guestgrowth-lead'
      path: '/api/public/guestgrowth-lead'
      fullPath: '/api/public/guestgrowth-lead'
      preLoaderRoute: typeof ApiPublicGuestgrowthLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discount-signup': {
      id: '/api/public/discount-signup'
      path: '/api/public/discount-signup'
      fullPath: '/api/public/discount-signup'
      preLoaderRoute: typeof ApiPublicDiscountSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ExploreRouteChildren {
  ExploreSlugRoute: typeof ExploreSlugRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreSlugRoute: ExploreSlugRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRouteWithChildren,
  MapRoute: MapRoute,
  PropertiesRoute: PropertiesRoute,
  ReviewsRoute: ReviewsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GuestgrowthSampleRoute: GuestgrowthSampleRoute,
  ListingsSlugRoute: ListingsSlugRoute,
  PlaqueSlugRoute: PlaqueSlugRoute,
  WifiSlugRoute: WifiSlugRoute,
  GuestgrowthIndexRoute: GuestgrowthIndexRoute,
  ApiPublicDiscountSignupRoute: ApiPublicDiscountSignupRoute,
  ApiPublicGuestgrowthLeadRoute: ApiPublicGuestgrowthLeadRoute,
  ApiPublicOrphanDayUpsellRoute: ApiPublicOrphanDayUpsellRoute,
  ApiPublicPostCheckoutMessageRoute: ApiPublicPostCheckoutMessageRoute,
  ApiPublicPreArrivalMessageRoute: ApiPublicPreArrivalMessageRoute,
  ApiPublicProcessUpsellRepliesRoute: ApiPublicProcessUpsellRepliesRoute,
  ApiPublicRebookingCampaignRoute: ApiPublicRebookingCampaignRoute,
  ApiPublicRefreshReviewsRoute: ApiPublicRefreshReviewsRoute,
  ApiPublicWifiSignupRoute: ApiPublicWifiSignupRoute,
  DevEmailPreviewTemplateRoute: DevEmailPreviewTemplateRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
